contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "conventional:comments"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

disableKinds = ["taxonomy", "taxonomyTerm", "i18n"]

[Params]
  subtitle = ""
  logo = "favicon.ico"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "souldzin"
  email = "souldzin@souldzin.com"
  gitlab = "souldzin"
  github = "souldzin"
  twitter = "souldzin"
  stackoverflow = "users/1708147/souldzin"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
