contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Conventional Comments"

DefaultContentLanguage = "ru"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

disableKinds = ["taxonomy", "taxonomyTerm", "i18n"]

[Params]
  subtitle = "Комментарии, которые легко прочесть и понять "
  logo = "logo.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  repository = "https://gitlab.com/conventionalcomments/conventionalcomments.gitlab.io"
  repositoryRu = "https://github.com/kotrikd/conventionalcomments-ru"

[Author]
  name = "Paul Slaughter"
  email = "contact@souldzin.com"
  gitlab = "souldzin"
  github = "souldzin"
  twitter = "souldzin"
  stackoverflow = "users/1708147/souldzin"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
