# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/conventionalcomments/hugo_node:0.62.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
